package com.pizza73.ws.industrymailout.subscriber;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1 2012-07-30T15:57:12.922-06:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", name = "SubscriberManagerSoap")
@XmlSeeAlso({ ObjectFactory.class })
public interface SubscriberManagerSoap
{

    @WebResult(name = "ConfirmSubscriberResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "ConfirmSubscriber", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.ConfirmSubscriber")
    @WebMethod(operationName = "ConfirmSubscriber", action = "http://www.mymailout.net/WebService/SubscriberManager/ConfirmSubscriber")
    @ResponseWrapper(localName = "ConfirmSubscriberResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.ConfirmSubscriberResponse")
    public com.pizza73.ws.industrymailout.subscriber.UpdateResult confirmSubscriber(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "email", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String email);

    @WebResult(name = "CreateAutoResponseEventTriggersResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "CreateAutoResponseEventTriggers", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.CreateAutoResponseEventTriggers")
    @WebMethod(operationName = "CreateAutoResponseEventTriggers", action = "http://www.mymailout.net/WebService/SubscriberManager/CreateAutoResponseEventTriggers")
    @ResponseWrapper(localName = "CreateAutoResponseEventTriggersResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.CreateAutoResponseEventTriggersResponse")
    public com.pizza73.ws.industrymailout.subscriber.UpdateResult createAutoResponseEventTriggers(
        @WebParam(name = "subscriberEmail", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String subscriberEmail,
        @WebParam(name = "autoresponseid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int autoresponseid,
        @WebParam(name = "extraSubscriberData", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") com.pizza73.ws.industrymailout.subscriber.ArrayOfStringKeyValuePair extraSubscriberData);

    @WebResult(name = "GetMailingListsResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "GetMailingLists", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetMailingLists")
    @WebMethod(operationName = "GetMailingLists", action = "http://www.mymailout.net/WebService/SubscriberManager/GetMailingLists")
    @ResponseWrapper(localName = "GetMailingListsResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetMailingListsResponse")
    public com.pizza73.ws.industrymailout.subscriber.ArrayOfMailingList getMailingLists();

    @WebResult(name = "RetrieveSubscriberRequestResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "RetrieveSubscriberRequest", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.RetrieveSubscriberRequest")
    @WebMethod(operationName = "RetrieveSubscriberRequest", action = "http://www.mymailout.net/WebService/SubscriberManager/RetrieveSubscriberRequest")
    @ResponseWrapper(localName = "RetrieveSubscriberRequestResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.RetrieveSubscriberRequestResponse")
    public com.pizza73.ws.industrymailout.subscriber.SubscriptionRequest retrieveSubscriberRequest(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "confirmationToken", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String confirmationToken);

    @WebResult(name = "AddSubscriberToSublistResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "AddSubscriberToSublist", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.AddSubscriberToSublist")
    @WebMethod(operationName = "AddSubscriberToSublist", action = "http://www.mymailout.net/WebService/SubscriberManager/AddSubscriberToSublist")
    @ResponseWrapper(localName = "AddSubscriberToSublistResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.AddSubscriberToSublistResponse")
    public com.pizza73.ws.industrymailout.subscriber.UpdateResult addSubscriberToSublist(
        @WebParam(name = "email", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String email,
        @WebParam(name = "sublistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int sublistid);

    @WebResult(name = "SignupNewSubscriberToSublistResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "SignupNewSubscriberToSublist", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.SignupNewSubscriberToSublist")
    @WebMethod(operationName = "SignupNewSubscriberToSublist", action = "http://www.mymailout.net/WebService/SubscriberManager/SignupNewSubscriberToSublist")
    @ResponseWrapper(localName = "SignupNewSubscriberToSublistResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.SignupNewSubscriberToSublistResponse")
    public com.pizza73.ws.industrymailout.subscriber.UpdateResult signupNewSubscriberToSublist(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "subscriber", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") com.pizza73.ws.industrymailout.subscriber.Subscriber subscriber,
        @WebParam(name = "checkrequired", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean checkrequired,
        @WebParam(name = "sublistids", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") com.pizza73.ws.industrymailout.subscriber.ArrayOfInt sublistids);

    @WebResult(name = "AddNewSublistResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "AddNewSublist", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.AddNewSublist")
    @WebMethod(operationName = "AddNewSublist", action = "http://www.mymailout.net/WebService/SubscriberManager/AddNewSublist")
    @ResponseWrapper(localName = "AddNewSublistResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.AddNewSublistResponse")
    public com.pizza73.ws.industrymailout.subscriber.SubList addNewSublist(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "name", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String name);

    @RequestWrapper(localName = "DeleteSublist", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.DeleteSublist")
    @WebMethod(operationName = "DeleteSublist", action = "http://www.mymailout.net/WebService/SubscriberManager/DeleteSublist")
    @ResponseWrapper(localName = "DeleteSublistResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.DeleteSublistResponse")
    public void deleteSublist(
        @WebParam(name = "sublistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int sublistid);

    @WebResult(name = "SignupNewSubscriberResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "SignupNewSubscriber", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.SignupNewSubscriber")
    @WebMethod(operationName = "SignupNewSubscriber", action = "http://www.mymailout.net/WebService/SubscriberManager/SignupNewSubscriber")
    @ResponseWrapper(localName = "SignupNewSubscriberResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.SignupNewSubscriberResponse")
    public com.pizza73.ws.industrymailout.subscriber.UpdateResult signupNewSubscriber(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "subscriber", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") com.pizza73.ws.industrymailout.subscriber.Subscriber subscriber,
        @WebParam(name = "checkrequired", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean checkrequired);

    @WebResult(name = "SubmitCsvFileResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "SubmitCsvFile", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.SubmitCsvFile")
    @WebMethod(operationName = "SubmitCsvFile", action = "http://www.mymailout.net/WebService/SubscriberManager/SubmitCsvFile")
    @ResponseWrapper(localName = "SubmitCsvFileResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.SubmitCsvFileResponse")
    public int submitCsvFile(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "descriptor", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") com.pizza73.ws.industrymailout.subscriber.CsvFileDescriptor descriptor,
        @WebParam(name = "csvcontents", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String csvcontents);

    @WebResult(name = "LoginResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "Login", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.Login")
    @WebMethod(operationName = "Login", action = "http://www.mymailout.net/WebService/SubscriberManager/Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.LoginResponse")
    public com.pizza73.ws.industrymailout.subscriber.LoginResult login(
        @WebParam(name = "username", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String password);

    @WebResult(name = "SubmitCsvFileWithSublistResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "SubmitCsvFileWithSublist", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.SubmitCsvFileWithSublist")
    @WebMethod(operationName = "SubmitCsvFileWithSublist", action = "http://www.mymailout.net/WebService/SubscriberManager/SubmitCsvFileWithSublist")
    @ResponseWrapper(localName = "SubmitCsvFileWithSublistResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.SubmitCsvFileWithSublistResponse")
    public int submitCsvFileWithSublist(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "descriptor", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") com.pizza73.ws.industrymailout.subscriber.CsvFileDescriptor descriptor,
        @WebParam(name = "csvcontents", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String csvcontents,
        @WebParam(name = "sublistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int sublistid,
        @WebParam(name = "clearsublist", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean clearsublist);

    @RequestWrapper(localName = "CleanupAfterCsvUpload", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.CleanupAfterCsvUpload")
    @WebMethod(operationName = "CleanupAfterCsvUpload", action = "http://www.mymailout.net/WebService/SubscriberManager/CleanupAfterCsvUpload")
    @ResponseWrapper(localName = "CleanupAfterCsvUploadResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.CleanupAfterCsvUploadResponse")
    public void cleanupAfterCsvUpload(
        @WebParam(name = "csvuploadid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int csvuploadid);

    @WebResult(name = "GetAllSubscribersAsCSVResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "GetAllSubscribersAsCSV", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetAllSubscribersAsCSV")
    @WebMethod(operationName = "GetAllSubscribersAsCSV", action = "http://www.mymailout.net/WebService/SubscriberManager/GetAllSubscribersAsCSV")
    @ResponseWrapper(localName = "GetAllSubscribersAsCSVResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetAllSubscribersAsCSVResponse")
    public java.lang.String getAllSubscribersAsCSV(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid);

    @WebResult(name = "GetSubscribersAsCSVResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "GetSubscribersAsCSV", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetSubscribersAsCSV")
    @WebMethod(operationName = "GetSubscribersAsCSV", action = "http://www.mymailout.net/WebService/SubscriberManager/GetSubscribersAsCSV")
    @ResponseWrapper(localName = "GetSubscribersAsCSVResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetSubscribersAsCSVResponse")
    public java.lang.String getSubscribersAsCSV(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "includeUnsubscribed", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean includeUnsubscribed,
        @WebParam(name = "includeActive", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean includeActive,
        @WebParam(name = "includeUnconfirmed", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean includeUnconfirmed,
        @WebParam(name = "utcStartDate", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") javax.xml.datatype.XMLGregorianCalendar utcStartDate,
        @WebParam(name = "ignoreNewCsvUploads", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean ignoreNewCsvUploads,
        @WebParam(name = "ignoreNewWebServiceUploads", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean ignoreNewWebServiceUploads);

    @WebResult(name = "GetSublistsAdvancedResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "GetSublistsAdvanced", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetSublistsAdvanced")
    @WebMethod(operationName = "GetSublistsAdvanced", action = "http://www.mymailout.net/WebService/SubscriberManager/GetSublistsAdvanced")
    @ResponseWrapper(localName = "GetSublistsAdvancedResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetSublistsAdvancedResponse")
    public com.pizza73.ws.industrymailout.subscriber.ArrayOfSubList getSublistsAdvanced(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "activeonly", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean activeonly,
        @WebParam(name = "subscriberformvarsonly", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean subscriberformvarsonly);

    @WebResult(name = "RemoveSubscriberFromSublistResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "RemoveSubscriberFromSublist", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.RemoveSubscriberFromSublist")
    @WebMethod(operationName = "RemoveSubscriberFromSublist", action = "http://www.mymailout.net/WebService/SubscriberManager/RemoveSubscriberFromSublist")
    @ResponseWrapper(localName = "RemoveSubscriberFromSublistResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.RemoveSubscriberFromSublistResponse")
    public com.pizza73.ws.industrymailout.subscriber.UpdateResult removeSubscriberFromSublist(
        @WebParam(name = "email", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String email,
        @WebParam(name = "sublistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int sublistid);

    @WebResult(name = "GetSpecialFieldValuesResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "GetSpecialFieldValues", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetSpecialFieldValues")
    @WebMethod(operationName = "GetSpecialFieldValues", action = "http://www.mymailout.net/WebService/SubscriberManager/GetSpecialFieldValues")
    @ResponseWrapper(localName = "GetSpecialFieldValuesResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetSpecialFieldValuesResponse")
    public com.pizza73.ws.industrymailout.subscriber.ArrayOfSpecialFieldEnumValue getSpecialFieldValues(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "fieldnumber", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int fieldnumber);

    @WebResult(name = "GetSublistsByGroupsResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "GetSublistsByGroups", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetSublistsByGroups")
    @WebMethod(operationName = "GetSublistsByGroups", action = "http://www.mymailout.net/WebService/SubscriberManager/GetSublistsByGroups")
    @ResponseWrapper(localName = "GetSublistsByGroupsResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetSublistsByGroupsResponse")
    public com.pizza73.ws.industrymailout.subscriber.ArrayOfSubListGroup getSublistsByGroups(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "activeonly", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean activeonly,
        @WebParam(name = "subscriberformvarsonly", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean subscriberformvarsonly);

    @WebResult(name = "GetAllSubscribersResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "GetAllSubscribers", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetAllSubscribers")
    @WebMethod(operationName = "GetAllSubscribers", action = "http://www.mymailout.net/WebService/SubscriberManager/GetAllSubscribers")
    @ResponseWrapper(localName = "GetAllSubscribersResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetAllSubscribersResponse")
    public com.pizza73.ws.industrymailout.subscriber.ArrayOfSubscriber getAllSubscribers(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid);

    @RequestWrapper(localName = "AppendCsvFile", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.AppendCsvFile")
    @WebMethod(operationName = "AppendCsvFile", action = "http://www.mymailout.net/WebService/SubscriberManager/AppendCsvFile")
    @ResponseWrapper(localName = "AppendCsvFileResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.AppendCsvFileResponse")
    public void appendCsvFile(
        @WebParam(name = "csvuploadid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int csvuploadid,
        @WebParam(name = "csvcontents", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String csvcontents);

    @WebResult(name = "GetMailingListResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "GetMailingList", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetMailingList")
    @WebMethod(operationName = "GetMailingList", action = "http://www.mymailout.net/WebService/SubscriberManager/GetMailingList")
    @ResponseWrapper(localName = "GetMailingListResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetMailingListResponse")
    public com.pizza73.ws.industrymailout.subscriber.MailingList getMailingList(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid);

    @WebResult(name = "GetRemovedSubscribersResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "GetRemovedSubscribers", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetRemovedSubscribers")
    @WebMethod(operationName = "GetRemovedSubscribers", action = "http://www.mymailout.net/WebService/SubscriberManager/GetRemovedSubscribers")
    @ResponseWrapper(localName = "GetRemovedSubscribersResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetRemovedSubscribersResponse")
    public com.pizza73.ws.industrymailout.subscriber.ArrayOfSubscriber getRemovedSubscribers(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "utcStartDate", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") javax.xml.datatype.XMLGregorianCalendar utcStartDate,
        @WebParam(name = "removalreasonid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int removalreasonid);

    @WebResult(name = "GetSublistsResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "GetSublists", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetSublists")
    @WebMethod(operationName = "GetSublists", action = "http://www.mymailout.net/WebService/SubscriberManager/GetSublists")
    @ResponseWrapper(localName = "GetSublistsResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetSublistsResponse")
    public com.pizza73.ws.industrymailout.subscriber.ArrayOfSubList getSublists(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid);

    @WebResult(name = "UpdateSubscriberResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "UpdateSubscriber", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.UpdateSubscriber")
    @WebMethod(operationName = "UpdateSubscriber", action = "http://www.mymailout.net/WebService/SubscriberManager/UpdateSubscriber")
    @ResponseWrapper(localName = "UpdateSubscriberResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.UpdateSubscriberResponse")
    public com.pizza73.ws.industrymailout.subscriber.UpdateResult updateSubscriber(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "origEmailAddress", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String origEmailAddress,
        @WebParam(name = "subscriber", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") com.pizza73.ws.industrymailout.subscriber.Subscriber subscriber,
        @WebParam(name = "checkrequired", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean checkrequired);

    @WebResult(name = "UnsubscribeResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "Unsubscribe", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.Unsubscribe")
    @WebMethod(operationName = "Unsubscribe", action = "http://www.mymailout.net/WebService/SubscriberManager/Unsubscribe")
    @ResponseWrapper(localName = "UnsubscribeResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.UnsubscribeResponse")
    public com.pizza73.ws.industrymailout.subscriber.UpdateResult unsubscribe(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "email", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String email);

    @WebResult(name = "UpdateSubscriberWithSublistsResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "UpdateSubscriberWithSublists", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.UpdateSubscriberWithSublists")
    @WebMethod(operationName = "UpdateSubscriberWithSublists", action = "http://www.mymailout.net/WebService/SubscriberManager/UpdateSubscriberWithSublists")
    @ResponseWrapper(localName = "UpdateSubscriberWithSublistsResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.UpdateSubscriberWithSublistsResponse")
    public com.pizza73.ws.industrymailout.subscriber.UpdateResult updateSubscriberWithSublists(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "origEmailAddress", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String origEmailAddress,
        @WebParam(name = "subscriber", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") com.pizza73.ws.industrymailout.subscriber.Subscriber subscriber,
        @WebParam(name = "checkrequired", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean checkrequired,
        @WebParam(name = "sublistids", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") com.pizza73.ws.industrymailout.subscriber.ArrayOfInt sublistids,
        @WebParam(name = "clearOldSublists", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean clearOldSublists);

    @WebResult(name = "RegisterSubscriptionRequestResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "RegisterSubscriptionRequest", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.RegisterSubscriptionRequest")
    @WebMethod(operationName = "RegisterSubscriptionRequest", action = "http://www.mymailout.net/WebService/SubscriberManager/RegisterSubscriptionRequest")
    @ResponseWrapper(localName = "RegisterSubscriptionRequestResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.RegisterSubscriptionRequestResponse")
    public java.lang.String registerSubscriptionRequest(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "email", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String email,
        @WebParam(name = "datafield", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String datafield,
        @WebParam(name = "expiryDateUTC", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") javax.xml.datatype.XMLGregorianCalendar expiryDateUTC);

    @WebResult(name = "AddToSuppressionListResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "AddToSuppressionList", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.AddToSuppressionList")
    @WebMethod(operationName = "AddToSuppressionList", action = "http://www.mymailout.net/WebService/SubscriberManager/AddToSuppressionList")
    @ResponseWrapper(localName = "AddToSuppressionListResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.AddToSuppressionListResponse")
    public int addToSuppressionList(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "email", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String email);

    @WebResult(name = "SendConfirmationEmailResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "SendConfirmationEmail", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.SendConfirmationEmail")
    @WebMethod(operationName = "SendConfirmationEmail", action = "http://www.mymailout.net/WebService/SubscriberManager/SendConfirmationEmail")
    @ResponseWrapper(localName = "SendConfirmationEmailResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.SendConfirmationEmailResponse")
    public com.pizza73.ws.industrymailout.subscriber.UpdateResult sendConfirmationEmail(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "email", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String email,
        @WebParam(name = "ipaddress", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String ipaddress);

    @WebResult(name = "ProcessCsvUploadResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "ProcessCsvUpload", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.ProcessCsvUpload")
    @WebMethod(operationName = "ProcessCsvUpload", action = "http://www.mymailout.net/WebService/SubscriberManager/ProcessCsvUpload")
    @ResponseWrapper(localName = "ProcessCsvUploadResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.ProcessCsvUploadResponse")
    public com.pizza73.ws.industrymailout.subscriber.UploadReport processCsvUpload(
        @WebParam(name = "csvUploadId", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int csvUploadId,
        @WebParam(name = "maxErrors", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int maxErrors);

    @WebResult(name = "GetSubscribersResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "GetSubscribers", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetSubscribers")
    @WebMethod(operationName = "GetSubscribers", action = "http://www.mymailout.net/WebService/SubscriberManager/GetSubscribers")
    @ResponseWrapper(localName = "GetSubscribersResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetSubscribersResponse")
    public com.pizza73.ws.industrymailout.subscriber.ArrayOfSubscriber getSubscribers(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "includeUnsubscribed", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean includeUnsubscribed,
        @WebParam(name = "includeActive", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean includeActive,
        @WebParam(name = "includeUnconfirmed", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean includeUnconfirmed,
        @WebParam(name = "utcStartDate", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") javax.xml.datatype.XMLGregorianCalendar utcStartDate,
        @WebParam(name = "ignoreNewCsvUploads", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean ignoreNewCsvUploads,
        @WebParam(name = "ignoreNewWebServiceUploads", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean ignoreNewWebServiceUploads);

    @WebResult(name = "AddSubscriberToSublistsResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "AddSubscriberToSublists", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.AddSubscriberToSublists")
    @WebMethod(operationName = "AddSubscriberToSublists", action = "http://www.mymailout.net/WebService/SubscriberManager/AddSubscriberToSublists")
    @ResponseWrapper(localName = "AddSubscriberToSublistsResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.AddSubscriberToSublistsResponse")
    public com.pizza73.ws.industrymailout.subscriber.UpdateResult addSubscriberToSublists(
        @WebParam(name = "email", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String email,
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "sublistids", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") com.pizza73.ws.industrymailout.subscriber.ArrayOfInt sublistids,
        @WebParam(name = "removeFromCurrentSublists", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean removeFromCurrentSublists,
        @WebParam(name = "ignoreHiddenSublists", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean ignoreHiddenSublists);

    @WebResult(name = "GetAllTriggersResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "GetAllTriggers", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetAllTriggers")
    @WebMethod(operationName = "GetAllTriggers", action = "http://www.mymailout.net/WebService/SubscriberManager/GetAllTriggers")
    @ResponseWrapper(localName = "GetAllTriggersResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetAllTriggersResponse")
    public com.pizza73.ws.industrymailout.subscriber.ArrayOfAutoResponseTrigger getAllTriggers(
        @WebParam(name = "subscriberEmail", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String subscriberEmail,
        @WebParam(name = "mailingListId", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailingListId,
        @WebParam(name = "excludeComplete", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") boolean excludeComplete);

    @WebResult(name = "GetSublistsForSubscriberResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "GetSublistsForSubscriber", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetSublistsForSubscriber")
    @WebMethod(operationName = "GetSublistsForSubscriber", action = "http://www.mymailout.net/WebService/SubscriberManager/GetSublistsForSubscriber")
    @ResponseWrapper(localName = "GetSublistsForSubscriberResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.GetSublistsForSubscriberResponse")
    public com.pizza73.ws.industrymailout.subscriber.ArrayOfSubList getSublistsForSubscriber(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "email", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String email);

    @WebResult(name = "RemoveAutoresponseEventTriggersResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "RemoveAutoresponseEventTriggers", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.RemoveAutoresponseEventTriggers")
    @WebMethod(operationName = "RemoveAutoresponseEventTriggers", action = "http://www.mymailout.net/WebService/SubscriberManager/RemoveAutoresponseEventTriggers")
    @ResponseWrapper(localName = "RemoveAutoresponseEventTriggersResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.RemoveAutoresponseEventTriggersResponse")
    public com.pizza73.ws.industrymailout.subscriber.UpdateResult removeAutoresponseEventTriggers(
        @WebParam(name = "subscriberEmail", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String subscriberEmail,
        @WebParam(name = "autoresponseid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int autoresponseid);

    @WebResult(name = "FindSubscriberResult", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager")
    @RequestWrapper(localName = "FindSubscriber", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.FindSubscriber")
    @WebMethod(operationName = "FindSubscriber", action = "http://www.mymailout.net/WebService/SubscriberManager/FindSubscriber")
    @ResponseWrapper(localName = "FindSubscriberResponse", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager", className = "com.pizza73.industrymailout.subscriber.FindSubscriberResponse")
    public com.pizza73.ws.industrymailout.subscriber.Subscriber findSubscriber(
        @WebParam(name = "mailinglistid", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") int mailinglistid,
        @WebParam(name = "email", targetNamespace = "http://www.mymailout.net/WebService/SubscriberManager") java.lang.String email);
}
